name: ShellCheck SARIF
on: [push, pull_request]

permissions: {}  # Setting default permissions to none for enhanced security

jobs:
  shellcheck:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # to get PR metadata
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    name: ShellCheck Analysis
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    timeout-minutes: 3
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Shellcheck Scan
        uses: reactive-firewall/shellcheck-scan@v2.0-rc2
        with:  # optional arguments
          match: 'tests/* **/*.bash'
          publish-artifacts: true
        if: ${{ success() }}
